net-ssh/net-ssh

- lib/net/ssh/authentication/key_manager.rb
- test/authentication/test_key_manager.rb
For one of servers which I have access to I need to use custom SSH key. I'm not using my default SSH key, so I made a custom entry in my `~/.ssh/config` to handle that. I specified value for IdentityFile pointing to correct id_rsa file. I am able to ssh to the server with no issues at all. However, when I try to deploy using Capistano, it fails with an error `connection failed for: dev.domain.com (Errno::EISDIR: Is a directory @ io_fread - /home/kiela/workspace/ruby/project`. I started digging in Capistrano but found nothing which can cause this. I moved to Net::SSH and noticed that when no key was specified in options for `Net::SSH.start` it somehow sets keys to current directory and tries to open that directory as a file. `File.readable?` returns `true` as directory can be read but the …
> Check if SSH key is a file

- lib/net/ssh/authentication/pageant.rb
pageant.rb no longer works on Ruby 2.2 on Windows since the dl module has been removed.  This patch updates pageant.rb to use fiddle instead for ruby 2.2 and higher.  Pageant.rb tests all pass.
> Switch pageant.rb to use Fiddle

- lib/net/ssh/proxy/command.rb
This fixes a longstanding bug discovered by users of SSHKit: https://github.com/capistrano/sshkit/issues/150.
To summarize: when SSH connections are made in multiple threads using `ProxyCommand`, there is a small possibility that `Net::SSH.start` will fail with an error like this:
```
NoMethodError: undefined method `recv' for #<IO:fd 47>
```
I traced the problem down to Ruby itself. Apparently, defining singleton methods using this syntax (as is done by `proxy/command.rb`) is not thread safe:
```ruby
class << io
def send(data, flag)
write_nonblock(data)
end
def recv(size)
read_nonblock(size)
end
end
```
When executed in parallel by many threads, there is a small chance that the `recv` method will not be defined. As strange as this bug may seem, you can reproduce it consistently with this …
> Fix NoMethodError `recv` in multithreaded usage of Net::SSH::Proxy::Command

- lib/net/ssh.rb
- lib/net/ssh/authentication/key_manager.rb
- test/authentication/test_key_manager.rb
allow options[:passphrase] to be used with options[:non_interactive]
> don't prompt for passphrases in non-interactive mode

- README.rdoc
Security certificate details in the install section of the readme are referring to a certificate that no longer exists.
> Update outdated security certificate details in README.rdoc

- Rakefile
- net-ssh.gemspec
Because net-ssh 2.10.0 drops ruby 1.9 support, there needs to be a ruby
version specified to help prevent issues when 2.10.0+ is pulled down for
ruby 1.9 installations.  This may help address #260
> Add ruby 2.0+ requirement

- .gitignore
- Gemfile
- net-ssh.gemspec
Enables running `bundle install` to install gems required for development.
> Add a Gemfile to make it easier to set up a development environment

- .travis.yml
Builds starts quicker and we avoid the annoying warning at the start of the log.
> Activate the faster container based travis build

- lib/net/ssh.rb
- test/configs/proxy_remote_user
- test/start/test_options.rb
- test/test_config.rb
Fixes #189 
The existing option is used here: https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/proxy/command.rb#L45
The fact that `remote_user` wasn't added to `VALID_OPTIONS` seems to have been noted in the original PR to add support for `%r` to proxy commands, here: https://github.com/net-ssh/net-ssh/pull/139#issuecomment-35518045
Tests included, although there's not really anything to test `%r` *and* `remote_user` together.
> Accept existing option `remote_user` as valid

- lib/net/ssh/transport/session.rb
Keep backward compatibility with 2.9 at connection timeout exceptions.
> re-raise Errno::ETIMEDOU from Socket.tcp as Net::SSH::ConnectionTimeout

- lib/net/ssh/connection/session.rb
- test/connection/test_session.rb
The docs state that #exec will return a string, and an empty string would be consistent.  Currently `nil` is returned, and this should be documented.
> Document that Net::SSH::Connection::Session#exec! returns nil if there is no output from the remote command

- lib/net/ssh/authentication/key_manager.rb
Fixing #290 
Since OpenSSH wrapper produces argument errors when it fails to decode the key data without a password, adding it to the decryption errors rescue block.
AFAIK this shouldn't affect other scenarios since by the second run `ignore_decryption_errors` option will be set to `false`.
> Fix for key_data ArgumentError on load

- lib/net/ssh/authentication/pageant.rb
To avoid this message when the constants have been already initialized by other gem
> already initialized constant DL::RUBY_FREE #285

- lib/net/ssh.rb
- lib/net/ssh/transport/algorithms.rb
- lib/net/ssh/verifiers/secure.rb
Fix: https://github.com/net-ssh/net-ssh/issues/307
Fix: https://github.com/net-ssh/net-ssh/issues/232
Ref: https://github.com/capistrano/sshkit/issues/326
As suggested in https://github.com/net-ssh/net-ssh/issues/307#issuecomment-179345555.
I initially defaulted with `options[:known_hosts] = KnownHosts` in `Net::SSH.start`, but then I figured that some people might use only parts of `Net::SSH`, and so I think it's better to check the options in all the sub components.
@mfazekas @TiagoCardoso1983 what do you think of this implementation?
> Allow to substitute Net::SSH::KnownHosts with a custom implementation

- lib/net/ssh/transport/algorithms.rb
- lib/net/ssh/transport/session.rb
- lib/net/ssh/verifiers/secure.rb
- test/common.rb
As discussed here: https://github.com/net-ssh/net-ssh/pull/308#issuecomment-179682869
`KnownHosts.search_for` always re-parse from zero and is called twice per session. This PR centralize and memoize that lookup.
It has been identified as a hot spot during profiling. See https://github.com/capistrano/sshkit/issues/326#issuecomment-178899236 for more details.
@mfazekas @TiagoCardoso1983 how does it look?
> Memoize session host keys

- lib/net/ssh.rb
- lib/net/ssh/known_hosts.rb
- lib/net/ssh/verifiers/secure.rb
the object returned by search_for now has an add method so it's more encapsulated see #311
> Refactor HostKeys cache

- lib/net/ssh/verifiers/secure.rb
The regression was introduced in #320 
```
net/ssh/verifiers/secure.rb:41:in `process_cache_miss'
net/ssh/verifiers/secure.rb:33:in `verify'
net/ssh/verifiers/strict.rb:16:in `verify'
net/ssh/verifiers/lenient.rb:15:in `verify'
net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:173:in `verify_server_key'
net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:68:in `exchange_keys'
net/ssh/transport/algorithms.rb:363:in `exchange_keys'
net/ssh/transport/algorithms.rb:200:in `proceed!'
net/ssh/transport/algorithms.rb:191:in `send_kexinit'
net/ssh/transport/algorithms.rb:146:in `accept_kexinit'
net/ssh/transport/session.rb:209:in `block in poll_message'
net/ssh/transport/session.rb:187:in `loop'
net/ssh/transport/session.rb:187:in `poll_message'
net/ssh/transport/session.rb:224:in `block in …
```
> Fix Secure#verify call to process_cache_miss

- lib/net/ssh/connection/session.rb
- test/connection/test_session.rb
@mfazekas noticed this when reviewing https://github.com/net-ssh/net-ssh-multi/pull/8.
If keepalive is enabled and the wait parameter is given when starting the event loop, we should pass the minimum of the two values through to `IO#select`. Otherwise the event loop could block for too long, and keepalive packets would not be sent as often as they should be.
> Use minimum timeout when calling IO#select

- lib/net/ssh/connection/session.rb
- test/connection/test_session.rb
Related to https://github.com/net-ssh/net-ssh-multi/pull/17.
This is required in `Net::SSH::Multi`, so that the aggregated event loop can decide how frequently to wake up and run the callbacks.
> Add max_select_wait_time method

- lib/net/ssh.rb
- lib/net/ssh/authentication/key_manager.rb
- lib/net/ssh/authentication/methods/abstract.rb
- lib/net/ssh/authentication/methods/keyboard_interactive.rb
- lib/net/ssh/authentication/methods/password.rb
- lib/net/ssh/authentication/session.rb
- lib/net/ssh/key_factory.rb
- lib/net/ssh/prompt.rb
- test/authentication/methods/common.rb
- test/authentication/methods/test_keyboard_interactive.rb
- test/authentication/methods/test_password.rb
- test/authentication/test_key_manager.rb
- test/common.rb
- test/integration/playbook.yml
- test/integration/test_forward.rb
- test/integration/test_id_rsa_keys.rb
- test/integration/test_password.rb
- test/integration/test_proxy.rb
- test/test_key_factory.rb
Fixes: #91, and fixes #254, and fixes #293 
Changes:
- We use io/console so no termios/highline is required
- Password prompt logic now customizable via ```:password_prompt``` option. It should be possible to implement caching logic
- Keyboard interactive now asks multiple times if the provided credentials are incorrect
> Refactor prompting to a class that can be customized

- lib/net/ssh/test/channel.rb
- lib/net/ssh/test/packet.rb
- lib/net/ssh/test/script.rb
Fixes net-ssh/net-ssh#184
It does not support scripting custom PTY request arguments, but I believe it's useful even in this state. Since I haven't found any tests for `Net::SSH::Test`, I haven't added any, but tested this manually.
> Add Net::SSH::Test::Channel#sends_request_pty for scripting PTY requests

- lib/net/ssh.rb
- lib/net/ssh/authentication/agent/java_pageant.rb
- lib/net/ssh/authentication/agent/socket.rb
- lib/net/ssh/authentication/key_manager.rb
- lib/net/ssh/service/forward.rb
- test/authentication/test_agent.rb
Adding the option to specify a socket that will be used, this is useful in case we have multiple agents running and multiple users using the net-ssh at the same time (that's why changing the ENV variable is not really practical).
> Added ability to specify agent socket

- lib/net/ssh.rb
- lib/net/ssh/transport/algorithms.rb
- lib/net/ssh/transport/kex/diffie_hellman_group_exchange_sha1.rb
- test/transport/kex/test_diffie_hellman_group_exchange_sha1.rb
- test/transport/test_algorithms.rb
This commit introduces a new option, minimum_dh_bits. This option allows
the user to specify the minimum required bits for a diffie helman key
exchange in situations where the minimum hardcoded value of 1024 is too
weak.
> Adds minimum_dh_bits option.

- lib/net/ssh.rb
- test/start/test_options.rb
Allows it to handle logger being set explicitly to nil which may happen if options are wrapped by another program. Some discussion in #357
> set default options before checking for nils

- lib/net/ssh/transport/ctr.rb
Fixing defect #274
defining singleton methods using `class << obj... def` is not threadsafe. Using an alternative syntax to work around this issue
> Changing the syntax of singleton methods in CTR cipher

- CHANGES.txt
- lib/net/ssh/proxy/http.rb
- lib/net/ssh/proxy/https.rb
- test/integration/test_http_proxy.rb
Since the HTTP Proxy only supports BASIC authentication, this adds the
required infrastructure to net-ssh to connect to a SSL-enabled server.
Closes: #432
> Support HTTP Proxy on SSL socket

- README.rdoc
- net-ssh.gemspec
This gem doesn't install with JRuby because of the required Ruby version. It's looking for MRI > 2.0. This patch removes that dependency for MRI, and also fixes the `jruby-pageant` dependency. `RUBY_PLATFORM` returns 'java' for JRuby, so I changed it to `RUBY_ENGINE`.
> gemspec fixes for jruby sepcifics

- lib/net/ssh.rb
First attempt at Git Hub.. When calling 'configuration_for' there is no reason that I can find to specify a default value for ' use_ssh_config' because Hash#fetch called on 'options' will always either return what the user specified or True. Just a small Do not repeat yourself.
> Small DRY fix

- lib/net/ssh/authentication/key_manager.rb
- lib/net/ssh/buffer.rb
- lib/net/ssh/connection/session.rb
- lib/net/ssh/transport/algorithms.rb
- lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb
- lib/net/ssh/transport/openssl.rb
- test/integration/test_encoding.rb
- test/test_buffer.rb
This is a follow-on to backport #407 to the 3.x release branch.  This follows on from the discussion in #394 / #395 / #396 / #397
> UTF-8 buffer building encoding fixes - backport of #407

- CHANGES.txt
- lib/net/ssh/buffered_io.rb
- lib/net/ssh/connection/session.rb
- test/integration/test_channel.rb
When we have an exec and server closes transports  just afer sucessfull response to exec then we should not raise from the exec.
Fixes: #429
> dont raise from exec if server closes transport after

- test/common.rb
- test/integration/common.rb
- test/win_integration/common.rb
As both minitest and codecov runs from at_exit codedov should be called before minitest otherwise we collect codecov before running any tests.
> Codecov should be before minitest/autorun

- lib/net/ssh.rb
- test/start/test_options.rb
> Allow nil for passphrase, warn instead of raise with nil option errors

- lib/net/ssh/transport/algorithms.rb
- test/transport/test_algorithms.rb
Because I recently was also hit by https://github.com/net-ssh/net-ssh/issues/314, I wanted to help to get this feature into `Net::SSH`.
Two things I'm not totally sure about:
- when running `ssh -Q key` on my machine, I got a couple of algorithms that are not in the list of default ones. I guess that's fine, and that's also why I skipped validation for the algorithms added via `+` to the list
- I failed to find a reference (or lookup the source code of other implementations), but I think from the wording the `HostkeyAlgorithms` should only feature a single `+` sign, so that the whole line is added (vs a plus sign in front of each algorithm)
Let me know what you think - happy to update the PR!
Closes: #470
> Correctly parse '+' in config files

- lib/net/ssh/config.rb
- test/configs/conf.d/subset2
- test/configs/conf.d/subset3
- test/configs/include
- test/configs/subset1
- test/test_config.rb
Net::SSH supports for `Include` keyword since OpenSSH added an include directive for ssh_config on v7.3.
Ref: https://www.openssh.com/txt/release-7.3
Include directives are very useful for breaking down a large ssh_config into smaller files.
```
$ man ssh_config
...
Include
Include the specified configuration file(s).  Multiple pathnames may be
specified and each pathname may contain glob(3) wildcards and, for user
configurations, shell-like ``~'' references to user home directories.
Files without absolute paths are assumed to be in ~/.ssh if included in a
user configuration file or /etc/ssh if included from the system configu-
ration file.  Include directive may appear inside a Match or Host block
to perform conditional inclusion.
...
```
> Support for `Include` directive

- .travis.yml
- Gemfile
- Gemfile.norbnacl.lock
- lib/net/ssh/authentication/ed25519.rb
- lib/net/ssh/authentication/ed25519_loader.rb
- net-ssh.gemspec
Closes: #476
Improves error message if required dependencies not yet installed.
```sh
$ BUNDLE_GEMFILE=./Gemfile.norbnacl bundle exec irb
2.3.0 :001 > require 'net/ssh'
=> true 
2.3.0 :002 > Net::SSH.start('localhost','foo', {keys: 'test/keys/id_ed25519_pwd'})
NotImplementedError: unsupported key type `ssh-ed25519'
net-ssh requires the following gems for ed25519 support:
* rbnacl (>= 3.2, < 5.0)
* rbnacl-libsodium, if your system doesn't have libsodium installed.
* bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/478 for more information
Gem::LoadError : "rbnacl is not part of the bundle. Add it to Gemfile."
```
> Allow rbnacl 4 and better description on what to install

- lib/net/ssh.rb
- lib/net/ssh/config.rb
- test/test_config.rb
#351 partially fixed the expandable default files problem, but
Net::SSH.configuration_for still passes in the unfiltered default files,
bypassing the filtered defaults. This change exposes the
`expandable_default_files` method to allow Net::SSH to fall back to it,
to avoid the error:
```
ArgumentError: couldn't find HOME environment -- expanding `~'
```
> Always use Net::SSH::Config.expandable_default_files

- lib/net/ssh/transport/algorithms.rb
- test/transport/test_algorithms.rb
Removed the interpolation of a missing variable which would raise a `NameError` when a `Session` or `Algorithms` instance had a valid `logger` object regardless of log level.
Added a test that exercises the method in question, including an assertion that the output log includes the expected string.
> Fixed string interpolation issue (#483)

- lib/net/ssh/authentication/certificate.rb
- lib/net/ssh/authentication/ed25519.rb
- lib/net/ssh/authentication/key_manager.rb
- lib/net/ssh/buffer.rb
- lib/net/ssh/key_factory.rb
- lib/net/ssh/transport/openssl.rb
- test/authentication/test_certificate.rb
- test/authentication/test_key_manager.rb
This adds support for parsing and signing SSH certificates, and for using
SSH certificates as identities when authenticating, via a "-cert.pub" file.
This does not add support for authenticating host certificates.  Supporting
that requires understanding @cert-authority in known_hosts, and validating
the hostname against the certificate principals.
> Add support for SSH certificates for client authentication.

- lib/net/ssh/authentication/agent.rb
The agent detection fails if you have a mingw setup with a working ssh-agent. The ENV SSH_AUTH_SOCK is set, but windows fails to use the UnixSocket class.
```
E, [2017-01-25T09:46:15.783805 #75060] ERROR -- net.ssh.authentication.agent[24dcda0]: could not connect to ssh-agent: uninitialized constant Net::SSH::Authentication::Agent::UNIXSocket
Did you mean?  Socket
IPSocket
UDPSocket
```
Tested on:
```
$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
```
> Fix agent detection on Windows

- .rubocop_todo.yml
- net-ssh.gemspec
rubocop: deprecation porting for 0.47.0
in rubocop 0.47 `MethodCallParentheses` was renamed to
`MethodCallWithoutArgsParentheses`.
Port to new name to silence deprecation warnings.
> rubocop: deprecation porting for 0.47.0

- lib/net/ssh/service/forward.rb
- test/integration/playbook.yml
- test/integration/test_forward.rb
- creates a unix domain socket on localhost
- requests a `direct-streamlocal@openssh.com` channel 
- sshd connects to remote unix domain socket
The channeling works exactly like `direct-tcpip`, only the "setup" part is different. This works with openssh 6.7+ https://github.com/openssh/openssh-portable/commit/7acefbbcbeab725420ea07397ae35992f505f702
I am a tad unsure how to properly test this. The current integration tests use ubuntu/trusty in vagrant, and trusty only had openssh 6.6. Options are probably to switch to ubuntu/xenial (16.04 LTS) or pretend there isn't much to test here (which actually is true given the only new code is creating a socket and the different channel type string).
Anyway, some input would be greatly appreciated.
> add direct-streamlocal@openssh.com support in Forward class

- lib/net/ssh/authentication/agent.rb
These were added in https://github.com/openssh/openssh-portable/commit/76c9fbbe35aabc1db977fb78e827644345e9442e and available since OpenSSH_7.2p1.
> New signature methods

- lib/net/ssh/config.rb
- test/configs/conf.d/subdir/subset4
- test/configs/conf.d/subset2
According to [ssh_config(5)](http://man.openbsd.org/ssh_config#Include), relative paths in the Include directive is relative from the directory of the root file, not from that of the including file.  If `~/.ssh/config` includes `~/.ssh/dir1/file1` which has a line `Include dir2/file2`, ssh tries to include `~/.ssh/dir2/file2`, not `~/.ssh/dir1/dir2/file2`.
> Resolve relative paths in the Include directive properly

- lib/net/ssh/config.rb
- test/configs/include
- test/configs/subset ws
- test/test_config.rb
ssh_config(5) from OpenSSH says an Include directive may take multiple pathnames. The pathnames are separated by whitespaces and may contain whitespaces when enclosed in double quotes.
> Support including multiple files by a single Include directive

- lib/net/ssh/transport/algorithms.rb
- test/transport/test_algorithms.rb
If a consumer used the default for the `:encryption` setting and the
host attempted to negotiate cipher suites with only supported suites
after `none` (but supported none), it would go ahead and use `none`
rather than the other supported cipher suites. This commit updates that
behavior to first allow Net::SSH to enumerate all of the possible
default cipher suites before ending on `none`.
> Move `none` cipher to end of cipher list

- lib/net/ssh/config.rb
- test/configs/conf.d/subset3
- test/configs/include
- test/test_config.rb
If configuration files have multiple identity files, Net::SSH should support those.
The [ssh_config manual](http://man.openbsd.org/ssh_config#IdentityFile) states:
> It is possible to have multiple identity files specified in configuration files; all these identities will be tried in sequence. 
We should merge `globals['identityfile']` with `settings['identityfile']` in loading configuration files.
> Support multiple identity files

- CHANGES.txt
- lib/net/ssh.rb
- lib/net/ssh/test.rb
- lib/net/ssh/transport/session.rb
- test/transport/test_session.rb
The words we choose matter. By using the word "paranoid", we make
fun of people who care about security. Instead, we should encourage
security in our community, or at least use a neutral term.
In this patch, we choose the neutral wording that is used by the SSH
manual page:
> the server must be able to verify the client's host key
> (see the description of /etc/ssh/ssh_known_hosts and
> ~/.ssh/known_hosts, below) for login to be permitted.
> Rename :paranoid to :verify_host_key

- Gemfile
In the Gemfile the byebug gem will not install as expected because RUBY_ENGINE != "mri"
Assuming [this](https://stackoverflow.com/questions/9894168/what-values-for-ruby-engine-correspond-to-which-ruby-implementations) is accurate and it appears to be in my experiments.
> MRI Ruby will show as ruby on RUBY_ENGINE

- lib/net/ssh/config.rb
- test/configs/match
- test/test_config.rb
issue: https://github.com/net-ssh/net-ssh/issues/374
This change makes Net::SSH::Config to recognize `Match` directive in ssh_config.
Only the `all` criteria keyword (and its negation) is supported at this time.
Though only supporting `all` is not very useful, it is important that net-ssh correctly handles block structure of ssh_config.
> Add initial Match support

- lib/net/ssh/transport/ctr.rb
#slice! in a loop gets expensive quickly when encrypting larger data blobs
(e.g. when uploading data through net-sftp).
#slice! needs to modify self AND create a new string for the substr,
#slice on the other hand only needs to do the latter.
as we do not need the modified remaining string in the loop we can simply
slice in the loop and then change remaining afterwards to modify the
string permanently.
Closes: #542
> improve CTR speed by not mutating the remaining string in a loop

- lib/net/ssh.rb
Fixes the docs for Net::SSH.start's `agent_socket_factory` option.
Currently, the example code provided in the docs is not correct and this PR fixes that. Here is what's wrong with the current version:
* `Net::SSH::start` versus `Net::SSH.start`
* Args out of order for `.start`
Let me know if I need to do anything else to land this fix!
Cheers,
Charles
> Fix Net::SSH.start docs

- lib/net/ssh/buffered_io.rb
- lib/net/ssh/connection/event_loop.rb
- lib/net/ssh/proxy/command.rb
- lib/net/ssh/ruby_compat.rb
- lib/net/ssh/transport/packet_stream.rb
- test/integration/test_proxy.rb
Despite the comment, it was not doing anything anymore except invoking the default `IO.select`.
> Remove Net::SSH::Compat.io_select

- .travis.yml
It looks like Ruby 2.0/2.1 are both broken for Travis CI testing because some upstream gems have stopped supporting these versions. Since these also are not receiving security updates, let's bump all tested Ruby versions to the latest supported releases, and remove the unsupported ones.
> disable broken rubies, update rubies with security issues

- lib/net/ssh/transport/openssl.rb
Closes: #503 
relative to net-ssh version 4.2.0 (released as gem)
Please note that I could not test this in the 5.0.0-beta1 version with my scripts using code like
```ruby
def executeRemote(command, builder)                                                                                                                                                            
Net::SSH.start(builder.hostname,builder.username,
:config => true, :compression => true) do |ssh|
stdout_data = ""
stderr_data = ""
exit_code   = nil
exit_signal = nil
ssh.open_channel do |channel|
channel.exec(command) do |ch, success|
unless success
raise "FAILED: couldn't execute command #{command}"
end
channel.on_data do |ch, data|
stdout_data += data
$stdout.write(data) if @debug
end
channel.on_extended_data do |ch, type, …
```
> Fix for current arch linux box using openssl-1.1.0g

- lib/net/ssh/config.rb
- test/test_config.rb
The `Net::SSH::Config::default_files` method is supposed to "return an array of locations" to parse by default.
However, it currently returns a **reference** to the actual `@@default_files` class variable, meaning that any API consumers who `Enumerable#shift`, `pop`, or otherwise modify the returned Array are actually **__modifying the state of the `Net::SSH` library as a whole__**, meaning that subsequent uses cannot use the same array contents.
----
I found this because I use `Net::SSH.start` by itself (eg, automagically getting configuration), but ran into problems when I added this block in front, where I'm simply loading the files to find whether a new option `IdentityAgent` is set. (Eg, I'm not otherwise using/`::translate`ing the loaded options: I'm still relying on `#start` to do …
> Fixed side-effects caused by passing by reference

- lib/net/ssh/proxy/http.rb
Some proxy servers require HTTP/1.1 with a Host header.
> Update proxy to HTTP/1.1

- lib/net/ssh/authentication/pageant.rb
From cygwin 2.5.2, dlopen needs an extension (https://cygwin.com/ml/cygwin/2016-06/msg00379.html). So add `.dll` suffix to all needed libraries.
Fixes #602
> Specify dll extension

- test/start/test_user_nil.rb
The goal of this test seems to be to confirm that the current user's login is used when ssh-ing.  However, it breaks when `~/.ssh/config` contains `User` directives which override the default login.
e.g.:
```
Host *
User chris_taylor
```
...will cause the test to fail as follows:
```
1) Failure:
NetSSH::TestStartUserNil#test_start_should_use_default_user_when_nil [/home/ctaylorr/work/net-ssh/test/start/test_user_nil.rb:22]:
unexpected invocation: #<Mock:authentication_session>.authenticate("ssh-connection", "chris_taylor", nil)
satisfied expectations:
- allowed any number of times, not yet invoked: #<Mock:authentication_session>.authenticate()
- allowed any number of times, invoked once: Net::SSH::Authentication::Session.new(any_parameters)
- allowed any number of times, invoked once: …
```
> Use empty config when testing default user

- lib/net/ssh/transport/cipher_factory.rb
while this doesn't cleanup the specs for jruby yet (a few issues are being fixed in jruby-openssl with `set_key` on pkey); it does allow net/ssh > 5 to work on Jruby as the ctr ciphers are not yet available in jruby-openssl
fixes issue #611
> fix net/ssh 5+ for jruby

- lib/net/ssh/authentication/methods/publickey.rb
for some reason when using wingftp server it is returning success that is not handled in the library and it was raising an exception.    
```
trying publickey (<fingerprint removed>)
D, [2018-07-11T11:52:06.075571 #16848] DEBUG -- net.ssh.authentication.methods.publickey[3fc7a4652b8c]: trying publickey (<fingerprint removed>)
D, [2018-07-11T11:52:06.075980 #16848] DEBUG -- socket[3fc7a47d0860]: queueing packet nr 4 type 50 len 604
D, [2018-07-11T11:52:06.076182 #16848] DEBUG -- socket[3fc7a47d0860]: sent 628 bytes
D, [2018-07-11T11:52:06.106931 #16848] DEBUG -- socket[3fc7a47d0860]: read 36 bytes
D, [2018-07-11T11:52:06.107231 #16848] DEBUG -- socket[3fc7a47d0860]: received packet nr 4 type 52 len 12
Net::SSH::Exception: unexpected reply to USERAUTH_REQUEST: 52 …
```
> fixing to work with windows and wingftpserver connecting with public key

- .travis.yml
Tiger CI has pthon 2.6 and there were ansible validation issues
> Fix ansible/rvm install on python

- lib/net/ssh/transport/openssl.rb
- test/test_buffer.rb
Fix an issue where writing an ECDSA public_key out to a Net::SSH::Buffer
fails when calling to_blob on the key due to the method being undefined.
Fixes https://github.com/net-ssh/net-ssh/issues/619
> Implement to_blob on OpenSSL::PKey::EC::Point

- lib/net/ssh/authentication/agent.rb
- lib/net/ssh/authentication/key_manager.rb
- lib/net/ssh/config.rb
This commit adds support for configuring the IdentityAgent through an SSH config file.
> Add support for IdentityAgent in ssh_config

- lib/net/ssh/authentication/agent.rb
- test/authentication/test_agent.rb
This PR fixes an issue where an invalid result was provided by the ssh-agent daemon when reading available identities. The root cause of the originating issue was within the gnome-keyring project where it would improperly read in v1 public keys and return invalid results. The result of which would be this error:
```
/gems/2.2.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/agent.rb:128:in `block in identities': can't modify frozen NilClass (RuntimeError)
```
Since `Buffer#read_key` will return `nil` on certain conditions, this PR validates the result is not `nil` before continuing on. If the result _is_ nil, it logs an error and continues on.
> Skip identities that provide invalid key

- lib/net/ssh/transport/algorithms.rb
- test/transport/test_algorithms.rb
This commit modifies Net::SSH to prefer strong encryption for HMAC,
Cipher, Host Key Authentication and Key Exchange operations. It should resolve #627.
> Prefer more modern cryptographic algorithms

- test/transport/test_session.rb
Otherwise there is an intermittent test failure depending on which order tests are loaded in. The Debian buildds have managed to hit this multiple times.
> Add missing 'logger' in test_session.rb.

- lib/net/ssh/test/extensions.rb
- lib/net/ssh/transport/packet_stream.rb
- lib/net/ssh/transport/session.rb
- test/transport/test_packet_stream.rb
- test/transport/test_session.rb
If the socket isn't closed properly for some reason this select will
block forever.
Fixes #550
> Add timeout to blocking next_packet IO.select

- lib/net/ssh/config.rb
- test/test_config.rb
Previously wasn't correctly handling quoted and `=` delimited values.
Also, fixes logic that unsupported `Match` conditions result in subsequent declarations to be applied for configuration.
OpenSSH implementation details:
- https://github.com/openssh/openssh-portable/blob/624d19ac2d56fa86a22417c35536caceb3be346f/readconf.c#L599
- https://github.com/openssh/openssh-portable/blob/624d19ac2d56fa86a22417c35536caceb3be346f/misc.c#L284-L285
---
Closes #631
> Improve processing of ssh_config Match conditions

- lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb
- lib/net/ssh/transport/session.rb
- lib/net/ssh/verifiers/accept_new.rb
- lib/net/ssh/verifiers/always.rb
- lib/net/ssh/verifiers/never.rb
- test/common.rb
- test/transport/test_session.rb
- test/verifiers/test_always.rb
In my environment I know that server key verification would fail so
I set `verify_host_key` to `:never` I see following error:
```
diffie_hellman_group1_sha1.rb:211:in `verify_signature': could not verify server signature (Net::SSH::Exception)
```
This PR updates the Verifiers to provide key verification as well as key signature so when setting
that this operation should never be run it works fine.
> Server key signature verification done even if not requested

- test/common.rb
Permits per-scenario/test setup in usual `setup/teardown` constructs
Issue was spotted on local development machine where `SSH_AUTH_SOCK` was
present in ENV list - it messed up with "test/authentication/test_session.rb" tests
> Clear SSH_AUTH_SOCK for duration of test run

- lib/net/ssh/authentication/key_manager.rb
- test/authentication/test_key_manager.rb
Fixes #668
At least in the issue example app's simple case.
The example app from issue
```
$ ruby example.rb
Enter passphrase for /Users/kimmo/.ssh/passphrase:
```
```
$ ruby example.rb
just asking..
just asking..
just asking..
```
> Pass :password_prompt to KeyFactory.load_private_key

- lib/net/ssh/transport/algorithms.rb
Summary
Failure to negotiate algorithms is a common cause of connection
difficulties. This adds helpful troubleshooting information to the
log (at the 'error' level), plus a suggestion to check the log. The
intent is to clarify the problem and make troubleshooting easier.
Motivation
It seems most Issue reports involving the "could not settle" exception are due to client or server mis-configuration, not problems with this gem.  This will increase people's ability to troubleshoot mis-configurations on their own, and reduce the workload on this gem's maintainers.
Background
Some examples of people reporting being stuck on the Net::SSH "could not settle" exception (and may have been able to troubleshoot on their own with additional details):
- …
> Log details of failure to negotiate algorithms

- lib/net/ssh/config.rb
- test/test_config.rb
Make this setting available so it can be used when deciding how to configure `verify_host_key` so that users of this library can enable behavior consistent with `ssh`.
Resolves #678.
> Expose StrictHostKeyChecking from SSH config

- net-ssh.gemspec
This PR solve the bundle 2.0 compatibility issue : 
```
$ bundle install
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
In Gemfile:
bundler (~> 1.11)
Current Bundler version:
bundler (2.0.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
Could not find gem 'bundler (~> 1.11)' in any of the relevant sources:
the local ruby installation
```
> Fix bundle 2.0 compatibility

- test/integration/Vagrantfile
- test/integration/playbook.yml
It looks `https://ftp.spline.de/pub/OpenBSD/OpenSSH/portable/openssh-7.4p1.tar.gz` is not working and on my mac i had to turn off `validate_certs` - sounds a python/openssl issue.
> Update vagran and playbook

- README.md
- lib/net/ssh/test.rb
- lib/net/ssh/transport/algorithms.rb
- test/transport/test_algorithms.rb
Following the issue #705, the unsecure algs are remove from default algs.
To be backward compatible until the next major version, just add the option `append_all_supported_algorithms: true`
> Remove unsecure algs by default

- net-ssh.gemspec
Reference: https://guides.rubygems.org/specification-reference/#metadata
> Add changelog_uri to metadata to easily link from rubygems.org

- lib/net/ssh/transport/algorithms.rb
- test/transport/test_algorithms.rb
Based on @brbrady's [earlier PR](https://github.com/net-ssh/net-ssh/pull/677), in case they don't see this and we want this merged.
Minor changes:
* `s/$1/Regexp.last_match[1]/`
* Slight test formatting
> Add support for all algorithms in Transport::Algorithms#host_key_format

- lib/net/ssh/authentication/ed25519.rb
- test/authentication/test_ed25519.rb
It resolves #731 
It just ignore extra newlines and white spaces.
> allow multiple newlines for OPENSSH PRIVATE KEY

- lib/net/ssh/loggable.rb
This PR is to replace `self.class.name` with `self.class.to_s` in Loggable module's facility method.
I tried including Net::SSH::Loggable module for an anonymous class in my code, but I got an error:
```
NoMethodError (undefined method `+' for nil:NilClass)
```
The reason was that the name method returns nil for the anonymous class. 
Since Ruby 1.9.1, name method returns nil for anonymous module/class.
On the other hand, to_s method returns the object's ID in String.
```
Class.new.name #=> nil
Class.new.to_s #=> "#<Class:0x00007fa22318efa8>"
```
So, for the safety, I suggest to replace name method with to_s method.
This PR must be no affect for the current Net::SSH library itself.
> Fix Loggable to use to_s method instead of name method for self.class

- lib/net/ssh/authentication/certificate.rb
The OpenSSH certificate format interpets a `valid_before` time of `2^64-1` (max for unsigned long) to mean "forever": https://github.com/openssh/openssh-portable/blob/master/sshkey.c#L3159
Golang also interprets it this way:
https://github.com/golang/crypto/blob/master/ssh/certs.go#L47
I'm running into a `RangeError` issue with net-ssh on JRuby for certificates that have been issued to be valid for 'forever', as JRuby uses a signed long, and also multiplies the passed value by 1000 (as the internal storage uses milliseconds). (https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyTime.java#L1280)
This caps the `cert.valid_before` at `0x20c49ba5e353f7` which is the largest value that can be handled by JRuby and which translates to `292278994-08-17 01:12:55 -0600`, …
> Limit cert.valid_before to max supported by JRuby

- .rubocop_todo.yml
- lib/net/ssh.rb
- lib/net/ssh/config.rb
- lib/net/ssh/connection/channel.rb
- test/configs/set_env
- test/integration/common.rb
- test/integration/playbook.yml
- test/integration/test_channel.rb
- test/integration/test_forward.rb
- test/start/test_options.rb
- test/test_config.rb
Closes #725.
This PR adds a new SSH option `set_env` that is supported in [OpenSSH 7.8](https://www.openssh.com/txt/release-7.8). For more info, please see #725.
> Add set_env option

- .travis.yml
In an effort to address #655 this enables the latest JRuby in Travis.
> Enable JRuby 9.2.11.1 in TravisCI

- CHANGES.txt
- lib/net/ssh/transport/algorithms.rb
- test/transport/test_algorithms.rb
hmac-sha2-512-etm@openssh.com hmac-sha2-256-etm@openssh.com opt in instead of default because of the currpoted hmac issue. 
See #728
See #714
> Make hmac-sha2-{256,512}-etm opt-in

- lib/net/ssh/transport/algorithms.rb
- test/transport/test_algorithms.rb
As per `man ssh_config` for KexAlgorithms, MACs, and similar options:
```
Multiple algorithms must be comma-separated. Alternately if the specified value begins with a '+' character, then the specified methods will be appended to the default set instead of replacing them.  If the specified value begins with a '-' character, then the specified methods (including wildcards) will be removed from the default set instead of replacing them.
```
Without this, having these subtraction options in your SSH config will replace the default algorithms and cause Net::SSH to raise with `Net::SSH::Exception` and "could not settle on host_key algorithm". i.e. If you set `HostKeyAlgorithms -ssh-rsa`, it uses `-ssh-rsa` as the algorithm, rather than removing `ssh-rsa` from the algorithm preferences.
> Support algorithm subtraction syntax from ssh_config

- lib/net/ssh/authentication/certificate.rb
This PR slightly reduces the max constant so that it is compatible with JRuby 9.1.
JRuby uses JodaTime under the hood. Until JodaTime 2.9 was released, while the year `292278994` was technically able to be stored, JodaTime didn't allow it because of undefined behavior at the edge of the numeric range (because of time zones and other issues). JodaTime 2.9 removed that undefined behavior, and now allows the year `292278994`. Details are available here: https://github.com/JodaOrg/joda-time/issues/190
JodaTime 2.9 was not pulled into JRuby until JRuby 9.2, so by slightly reducing this value, we can gain compatibility with JRuby 9.1.
```
irb(main):001:0> Time.at(0x20c49ba5e353f7)
RangeError: Value 292278994 for year must be in the range [-292275054,292278993]
from …
```
> Tweak max constant value to work with JRuby 9.1

- lib/net/ssh/transport/cipher_factory.rb
This re-adds the changes that were introduced in https://github.com/net-ssh/net-ssh/pull/612 and removed in https://github.com/net-ssh/net-ssh/pull/701.
While OpenSSL since 2012 has support for `aes-ctr`, the latest JRuby (9.2.11.1) still does not support them, which means that net-ssh 6 is broken for anyone using JRuby and has `aes-ctr` enabled on the server:
```
$ rbenv shell jruby-9.2.11.1
$ irb
irb(main):001:0> require 'openssl'
=> true
irb(main):002:0> ::OpenSSL::Cipher.ciphers.include?("aes-256-ctr")
=> false
irb(main):003:0> ::OpenSSL::Cipher.ciphers.include?("aes-192-ctr")
=> false
irb(main):004:0> ::OpenSSL::Cipher.ciphers.include?("aes-128-ctr")
```
> Re-add fix for JRuby

- .gitignore
- lib/net/ssh/authentication/certificate.rb
- lib/net/ssh/authentication/ed25519.rb
- lib/net/ssh/transport/algorithms.rb
- lib/net/ssh/transport/kex/abstract.rb
- lib/net/ssh/transport/openssl.rb
- test/integration/Vagrantfile
- test/integration/common.rb
- test/integration/playbook.yml
- test/transport/kex/test_ecdh_sha2_nistp256.rb
- test/transport/test_algorithms.rb
> Implemented rsa-sha2-512, rsa-sha2-256 host_key algs

- README.md
Using github.com for GitHub pages has been deprecated.
> Fix the documentation URL in the README

- lib/net/ssh/prompt.rb
`Net::SSH::Prompt::Prompter#ask` does not take three arguments, it takes two. Update the [docs](https://net-ssh.github.io/net-ssh/Net/SSH/Prompt.html) to reflect this.
> Update Net::SSH::Prompt usage documentation

- test/common.rb
Before
```
➜  net-ssh git:(master) bundle exec rake test
Mocha deprecation warning at ./net-ssh/test/common.rb:14:in `require': Require 'mocha/test_unit', 'mocha/minitest' or 'mocha/api' instead of 'mocha/setup'.
Run options: --seed 33461
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................. …
```
> Fix mocha deprecation warning

- .rubocop.yml
- CHANGES.txt
- Gemfile
- lib/net/ssh.rb
- lib/net/ssh/known_hosts.rb
- lib/net/ssh/transport/algorithms.rb
- lib/net/ssh/verifiers/always.rb
- test/integration/common.rb
- test/integration/playbook.yml
- test/integration/test_cert_host_auth.rb
- test/integration/test_channel.rb
- test/test_known_hosts.rb
- test/transport/test_algorithms.rb
Fixes: #613 
Implements `@cert-authority` marker in KnownHosts file.
1. If we see such marker, matching the connected host, we allow prioritize all cert-algs when negotiating with server.
https://github.com/net-ssh/net-ssh/blob/51dc78feac5dc9df615ca0ef82e707951887411c/lib/net/ssh/known_hosts.rb#L41-L47
2. If server sends a certificate , we verify that it's signed correctly and the signature matches what's in known hosts
https://github.com/net-ssh/net-ssh/blob/51dc78feac5dc9df615ca0ef82e707951887411c/lib/net/ssh/known_hosts.rb#L54-L60
Also changes `*` in `known_host` like in openssh this now includes dots and also a single `*` can be used to match any hosts.
TODO: We don't support `@revoke` yet, also if nonstandard port like `2213` used, the we only match`[hostname]:2213` against patterns …
> Cert based host auth

- lib/net/ssh/transport/openssl.rb
`OpenSSL::Pkey::EC::Point#ssh_signature_type` is missing.  
It should be an alias for the method `OpenSSL::Pkey::EC::Point#ssh_type`.
> Fix missing OpenSSL::Pkey::EC::Point#ssh_signature_type

- lib/net/ssh/config.rb
- test/test_config.rb
Translate `StrictHostKeyChecking` ssh config parameter to `:verify_host_key` parameter
Fixes: #764
> Fix StrictHostKeyChecking ssh config parameter translation

- lib/net/ssh/authentication/certificate.rb
- lib/net/ssh/authentication/ed25519.rb
- lib/net/ssh/authentication/key_manager.rb
- lib/net/ssh/authentication/methods/abstract.rb
- lib/net/ssh/authentication/methods/publickey.rb
- lib/net/ssh/authentication/session.rb
- lib/net/ssh/transport/openssl.rb
- test/authentication/methods/test_publickey.rb
- test/authentication/test_session.rb
Rebase from https://github.com/net-ssh/net-ssh/pull/811
> Added support for RSA client authentication with SHA-2

- lib/net/ssh/authentication/agent.rb
- test/authentication/test_agent.rb
`.ssh/config` supports paths in this style but `UNIXSocket.open` does not expand paths
Notably, environment variables like `$USER` are not supported by `ssh` for the `IdentityAgent` field so
```
Host *
IdentityAgent "~/Library/Application Support/xyz/agent.sock"
```
works; but
```
Host *
IdentityAgent "$USER/Library/Application Support/xyz/agent.sock"
```
does not
> Support `~` in the path to the SSH agent's unix socket

- lib/net/ssh/known_hosts.rb
File known_hosts.rb misses:
```
require 'delegate'
```
This causes following exception on f34:
```
/home/zzambers/.gem/ruby/gems/net-ssh-6.3.0.beta1/lib/net/ssh/known_hosts.rb:11:in `<module:HostKeyEntries>': uninitialized constant Net::SSH::HostKeyEntries::Delegator (NameError)
from /home/zzambers/.gem/ruby/gems/net-ssh-6.3.0.beta1/lib/net/ssh/known_hosts.rb:9:in `<module:SSH>'
from /home/zzambers/.gem/ruby/gems/net-ssh-6.3.0.beta1/lib/net/ssh/known_hosts.rb:8:in `<module:Net>'
from /home/zzambers/.gem/ruby/gems/net-ssh-6.3.0.beta1/lib/net/ssh/known_hosts.rb:7:in `<top (required)>'
from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
from …
```
> known_hosts.rb: Added missing require delegate

- test/integration/test_key_exchange.rb
The master branch don't work with the stdlib openssl 3.0 (include with ruby 3.1) with kex : diffie-hellman-group-exchange-sha256
> A integration test for all kex

- lib/net/ssh/connection/channel.rb
After upgrading to net-ssh 7.0.0, I get several lines like `E:TERM
V:xterm` printed in the terminal when connecting to hosts. I'm assuming
this slipped by mistake in commit 5e79b6687771 ("Fixed integration
test opensshd kill")
> Channel: drop debugging statement

- .github/workflows/ci-with-docker.yml
- .github/workflows/ci.yml
- .github/workflows/rubocop.yml
[andrewmcodes/rubocop-linter-action](https://github.com/andrewmcodes-archive/rubocop-linter-action) is deprecated and this PR replaces it.
I also bumped [actions/checkout](https://github.com/actions/checkout) to v3.
> Replace deprecated andrewmcodes/rubocop-linter-action

- lib/net/ssh/authentication/ed25519.rb
- test/authentication/test_ed25519.rb
In certain situations, `BCryptPbkdf::key` will return `nil` instead of deriving a key (https://github.com/net-ssh/bcrypt_pbkdf-ruby/blob/6e26b38cc8cfc43212d2fc709e7365cb77063b85/ext/mri/bcrypt_pbkdf.c#L111-L116) but the ED25519 authentication code assumes we'll always get a key, leading to a no method error later on.  This PR detects when we fail to derive a key and raises a `DecryptError`.
The error could possibly be an `ArgumentError` instead, we raise those when the given SSH key contains invalid parameters and we fail to derive a key due to invalid parameters as well.
One test here uses a pathological key that was generated to request zero rounds, the other passes a blank string for the password.  (Our upstream caller defaults a `nil` password to the string `"invalid"`, but allows …
> Raise error when BCryptPbkdf fails

- test/integration/test_handshake_timeout.rb
Added integration test for connection timeout handling.
See #900
> test: added integration test for connection timeout

- lib/net/ssh.rb
- test/start/test_options.rb
a45f54fe1de434605af0b7195dd9a91bccd2cec5 introduced the option to perform RSA client authentication using newer algorithm types, e.g. SHA2.
For me personally, this has broken `net-ssh` with a few servers. We use `net-ssh` in combination with `net-sftp` to communicate with a few obscure SSH implementations that we cannot control. It seems that some of these servers sent a disconnect when trying to authenticate with these newer algorithms, which are tried by default before the old SHA1 algorithm. This might also be the cause of #890, although the servers that we try to communicate with do actually still sent a disconnect packet (resulting in a `Net::SSH::Disconnect` exception), while that does not seem to be the case in #890.
a45f54fe1de434605af0b7195dd9a91bccd2cec5 also introduces the …
> Accept pubkey_algorithms option when starting a new connection

- .github/workflows/ci.yml
- CHANGES.txt
- DEVELOPMENT.md
- Gemfile.norbnacl
- lib/net/ssh/transport/algorithms.rb
- lib/net/ssh/transport/chacha20_poly1305_cipher.rb
- lib/net/ssh/transport/chacha20_poly1305_cipher_loader.rb
- lib/net/ssh/transport/cipher_factory.rb
- lib/net/ssh/transport/identity_cipher.rb
- lib/net/ssh/transport/openssl_cipher_extensions.rb
- lib/net/ssh/transport/packet_stream.rb
- lib/net/ssh/version.rb
- net-ssh.gemspec
- test/integration/common.rb
- test/integration/test_chacha20_poly1305_cipher.rb
- test/transport/test_algorithms.rb
- test/transport/test_cipher_factory.rb
- test/transport/test_packet_stream.rb
Fixes: #477 
Implementation of `chacha20-poly1305` chipher.
Since openssl has no separate poly implementation it useless RbNaCl for chacha20 and poly1305 implementation. So this feature is only enabled if you have rbnacl gem installed in your system.
TODO:
> chacha20-poly1305 with RbNaCl poly1305

- lib/net/ssh/authentication/methods/publickey.rb
Before this change it was not possible to distinguish between two public key authentications of the same key with different algorithms.
Which makes it difficult to see one attempt was failing with `USERAUTH_FAILURE`.
Similar things mentioned in https://github.com/net-ssh/net-ssh/issues/886
> Add debugging information for algorithm of pubkey in use

- lib/net/ssh/buffered_io.rb
Fixes "TypeError, no implicit conversion of nil into String" when reading from a closed stream. This error is related to a change in the behavior of Socket#recv which was introduced in Ruby 3.3.0.
See https://bugs.ruby-lang.org/issues/19899?issue_count=1&issue_position=1
> Ruby 3.3.0-preview2: Fix error when reading from a closed stream

- lib/net/ssh/authentication/ed25519.rb
- lib/net/ssh/authentication/pub_key_fingerprint.rb
- lib/net/ssh/known_hosts.rb
- net-ssh.gemspec
Starting in Ruby 3.3.0, `require "base64"` triggers a warning:
> base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec.
Rather than introduce a new dependency, this commit removes the base64 requirement in favor of using `String#pack` and `String#unpack1` directly. (The base64 gem is just a thin wrapper around these methods.)
I left base64 as a development dependency so that the existing tests could continue to use `Base64`, to confirm there are no regressions due to my changes.
The approach in this PR is similar to that used in several other gems, including:
- https://github.com/lostisland/faraday/pull/1541
- https://github.com/rack/rack/pull/2110
- https://github.com/rubocop/rubocop/pull/12313 …
> Remove base64 runtime dependency

- lib/net/ssh/authentication/ed25519.rb
- lib/net/ssh/known_hosts.rb
- test/authentication/test_key_manager.rb
- test/transport/kex/test_curve25519_sha256.rb
- test/transport/kex/test_diffie_hellman_group1_sha1.rb
- test/transport/kex/test_ecdh_sha2_nistp256.rb
The previous PR #932 refactored the code to no longer use the Base64 module, but forgot to remove the actual `require "base64"` statements. This follow up commit removes those requires to fix the following warning on Ruby 3.3:
> net/ssh/known_hosts.rb:3: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of net-ssh-7.2.2.rc1 to add base64 into its gemspec.
> Remove unused base64 requires to fix Ruby 3.3 warning

- .github/workflows/ci.yml
This PR adds Ruby 3.3.0 to CI matrix
> Add Ruby 3.3.0 to CI matrix

- .github/workflows/ci-with-docker.yml
- docker-compose.yml
This PR tries to get to a green build by using a Docker compose that's available in the GitHub Actions runner.
I ran the CI green 🟢  on my GitHub user's CI. Example: https://github.com/olleolleolle/net-ssh/actions/runs/11793676372
Builds in #960 exited with:
/home/runner/work/_temp/bd3752ef-77e4-46f1-8a33-b2c8277ccc85.sh: line 1: docker-compose: command not found
> CI: Fix builds by using "docker compose" rather than the removed docker-compose tool

- .github/workflows/ci.yml
We faced this issue at https://github.com/net-ssh/net-ssh/pull/976#issuecomment-3285208244.
Upgrade actions/cache version from 1 to 4 to fix the test failures.
https://github.com/net-ssh/net-ssh/actions/runs/17651350058/job/50226666721?pr=976
> Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: v1`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
> CI: Upgrade actions/cache version from 1 to 4

- .github/workflows/ci-with-docker.yml
- Dockerfile.zlib_ng
- test/transport/test_packet_stream.rb
@mfazekas, this PR is related to https://github.com/net-ssh/net-ssh/issues/965 and https://github.com/net-ssh/net-ssh/issues/975#issuecomment-3271384975, and adds the [zlib-ng](https://github.com/zlib-ng/zlib-ng) case in CI. The assertion failing in the zlib-ng case is skipped for now. Because I couldn't find an easy way to pass the failing assertion without hardcoding the expected results, and also it was hard to add the hardcoded strings for each cipher_method_name and hmac_method_name case.
Add zlib-ng case in CI using Fedora Linux that uses zlib-ng instead of zlib.
https://src.fedoraproject.org/rpms/zlib-ng
The assertion failing in the zlib-ng case is skipped for now.
What do you think?
> CI: Add zlib-ng case
