test/connection/test_session.rb, test/transport/kex/test_diffie_hellman_group1_sha1.rb, test/transport/kex/test_diffie_hellman_group_exchange_sha1.rb, test/transport/kex/test_diffie_hellman_group_exchange_sha256.rb
Running with different version of minitest  brought up those errors.
=> Fixed SHA256 tests

lib/net/ssh/authentication/pageant.rb
fix net-ssh not working with Pageant in 64-bit build. Problem was manually packing arrays into Win32 structures without taking alignment and 32bit/64bit field size discrepancies into account. 
Solved by using Fiddle Struct API - it packs correctly on both 32-bit and 64-bit system. 
Tested in both 32-bit and 64-bit Ruby (2.2.x, 2.1.x)
=> Fixing pageant interaction on 64-bit platform 

lib/net/ssh/authentication/key_manager.rb, test/authentication/test_key_manager.rb, test/integration/test_id_rsa_keys.rb
=> Public key can be loaded as private key. Fixes #238

lib/net/ssh/authentication/pageant.rb
The breakdown is introduced because of #221 
Just roughly tested by deploy several rails app and passed.
=> Use Fiddler on Ruby 2.1 for 64 bit compat on 2.1

lib/net/ssh/connection/session.rb, test/connection/test_session.rb
see https://github.com/net-ssh/net-ssh/pull/265
=> exec! should return empty string

test/integration/test_forward.rb
reproduces #280 in integration tests
=> Add more tests to reproduce forward issue with integration test

.travis.yml, test/transport/test_packet_stream.rb
- Add 2.3.0 to travis CI
- Fixed deprecated test
=> Ruby 2.3.0

lib/net/ssh/transport/server_version.rb, test/transport/test_server_version.rb
this allows for faster handshake - see #315
=> SSH2 we can send client id before server sent us theirs 

CHANGES.txt, lib/net/ssh/config.rb, test/test_config.rb
=> Fix incorrect pattern handling in config 

lib/net/ssh/known_hosts.rb
The regression was introduced in #320
Ref: https://github.com/net-ssh/net-ssh/pull/327
@mfazekas I missed that one until now because so far I had all the keys already added.
=> Fix KnownHosts#add reference to options

lib/net/ssh/proxy/http.rb
Modify net/ssh/proxy/http example: proxy.host -> proxy_host
=> Modify proxy usage example

lib/net/ssh.rb, lib/net/ssh/connection/session.rb, net-ssh.gemspec, test/connection/test_session.rb
=> Callbacks from channel open migth open new channels

lib/net/ssh/config.rb, lib/net/ssh/connection/session.rb, test/common.rb, test/connection/test_session.rb, test/integration/test_forward.rb, test/test_config.rb
=> ENV["HOME"] might be empty so filter non expandable paths

.travis.yml, lib/net/ssh/test/socket.rb, lib/net/ssh/transport/algorithms.rb, lib/net/ssh/transport/session.rb, test/transport/test_session.rb
=> Send KEXINIT asap

lib/net/ssh.rb, lib/net/ssh/authentication/agent/java_pageant.rb, lib/net/ssh/authentication/agent/socket.rb, lib/net/ssh/authentication/key_manager.rb, lib/net/ssh/service/forward.rb, test/authentication/test_agent.rb
backport to 3-1-release [https://github.com/net-ssh/net-ssh/pull/376]
@mfazekas thanks for the help!
=> Added ability to specify agent socket

lib/net/ssh/authentication/ed25519.rb, lib/net/ssh/authentication/ed25519_loader.rb, lib/net/ssh/buffer.rb, lib/net/ssh/key_factory.rb, test/authentication/test_ed25519.rb
=> Raise better error in read_keyblob if rbnacl is not available

.travis.yml, lib/net/ssh/authentication/pageant.rb
=> Fix issue #235

lib/net/ssh/connection/session.rb
=> Ignore Net::SSH::Disconnect when all channels closed

lib/net/ssh.rb
Combine bullet points. Alphabetize.
=> Docs: Combine docs for the :non_interactive option

CHANGES.txt, lib/net/ssh/connection/session.rb, net-ssh.gemspec, test/integration/common.rb, test/integration/test_exec.rb
=> Added .exitstatus to exec! return value

lib/net/ssh/transport/packet_stream.rb
=> Don't use fill if we have packet

CHANGES.txt, Gemfile, Gemfile.norbnacl, Gemfile.norbnacl.lock, lib/net/ssh/key_factory.rb, lib/net/ssh/transport/algorithms.rb, test/integration/common.rb, test/integration/test_ed25519_pkeys.rb, test/transport/test_algorithms.rb, test/transport/test_session.rb
=> Added ssh-ed25519 to HostKeys algorithms

.travis.yml, CHANGES.txt, Gemfile, lib/net/ssh.rb, lib/net/ssh/buffer.rb, lib/net/ssh/transport/cipher_factory.rb, lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb, test/integration/test_forward.rb, test/test_buffer.rb, test/test_key_factory.rb, test/test_known_hosts.rb
Closes #466
See https://github.com/ruby/openssl/issues/93#issuecomment-267359787
=> Fix OpenSSL 2 deprecation warnings

appveyor.yml, lib/net/ssh/authentication/pageant.rb
=> Added more ruby versions to windows tests

CHANGES.txt, lib/net/ssh/authentication/ed25519.rb, lib/net/ssh/authentication/ed25519_loader.rb
=> Gem load error

lib/net/ssh/authentication/ed25519.rb, test/integration/test_forward.rb
we care about rbnacl, rbnacl/libsodium is optional
=> Attempt to require rbnacl/libsodium, but don't care if not loaded, 

lib/net/ssh.rb, test/start/test_options.rb
=> fix typo in append_all_supported_algorithms

lib/net/ssh.rb, lib/net/ssh/proxy/command.rb, test/start/test_connection.rb
=> Close transport on proxy error

lib/net/ssh/transport/session.rb, test/transport/test_session.rb
Solving https://github.com/net-ssh/net-ssh/issues/512
Write some tests for this issue.
@imoverclocked, @mfazekas can you guys check is it right?
=> Fix debug output with proxy command

lib/net/ssh.rb, test/integration/test_password.rb, test/integration/test_proxy.rb, test/start/test_connection.rb
=> Test for proxy close and test for auth failure

.travis.yml, CHANGES.txt, Gemfile, Gemfile.noed25519, Gemfile.noed25519.lock, README.rdoc, appveyor.yml, lib/net/ssh/authentication/agent.rb, lib/net/ssh/authentication/ed25519.rb, lib/net/ssh/authentication/ed25519_loader.rb, lib/net/ssh/version.rb, net-ssh.gemspec, test/authentication/test_agent.rb, test/authentication/test_ed25519.rb, test/integration/test_cert_user_auth.rb, test/integration/test_ed25519_pkeys.rb
Closes: #563
Closes: #560
Closes: #555
=> Ed25519 gem

CHANGES.txt, lib/net/ssh/transport/cipher_factory.rb, lib/net/ssh/transport/ctr.rb, test/transport/test_cipher_factory.rb
=> Use OpenSSL for aes*-ctr

lib/net/ssh/transport/ctr.rb
=> Fix uninitialized SimpleDelegator

CHANGES.txt, lib/net/ssh/proxy/command.rb, test/proxy/test_command.rb, test/start/test_connection.rb
=> Handle ProxyCommand child in case of timeout and exception

lib/net/ssh/authentication/ed25519.rb, lib/net/ssh/authentication/pub_key_fingerprint.rb, lib/net/ssh/transport/openssl.rb, lib/net/ssh/version.rb, test/authentication/test_ed25519.rb, test/test_key_factory.rb
=> Sha fingerprint

lib/net/ssh/known_hosts.rb
=> removing unused arguments, flat_map better than map->flatten

.rubocop_todo.yml, lib/net/ssh/authentication/key_manager.rb, lib/net/ssh/authentication/session.rb, test/authentication/test_session.rb, test/common.rb
=> Dont use defaults when keydata

CHANGES.txt, lib/net/ssh/transport/packet_stream.rb
=> hmac instead of mac, confusing in networking environment

CHANGES.txt, lib/net/ssh.rb, lib/net/ssh/authentication/pub_key_fingerprint.rb, lib/net/ssh/config.rb, lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb, test/test_config.rb, test/transport/kex/test_diffie_hellman_group1_sha1.rb, test/transport/kex/test_ecdh_sha2_nistp256.rb
=> FingerprintHash SHA256|MD5

lib/net/ssh/config.rb, test/configs/match, test/test_config.rb
=> Add support for Host in Match config blocks

lib/net/ssh/connection/channel.rb
Fixes: net-ssh/net-scp/issues/39
Everytime local_window_size got less than half local_maximum_window_size we've increased both local_window_size and local_maximum_window_size, which meant that with large files we've increased local_maximum_window_size and eventually local_window_size beyond (1 << 31) which caused overflow on server side.
=> Don't keep increasing local_window_size beyond limits

README.rdoc
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/net-ssh❤️
It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README. [more info](https://github.com/opencollective/opencollective/wiki/Github-banner). See how it looks on this [repo](https://github.com/apex/apex#backers).
You can also add a postinstall script to let people know after npm|yarn install that you are welcoming donations (optional). [More info](https://github.com/OpenCollective/opencollective-cli)
You can also add …
=> Activating Open Collective

.travis.yml, lib/net/ssh/authentication/ed25519.rb, lib/net/ssh/key_factory.rb, lib/net/ssh/transport/algorithms.rb, test/README.txt, test/authentication/test_agent.rb, test/authentication/test_ed25519.rb, test/integration/README.md, test/integration/playbook.yml, test/integration/test_agent.rb, test/transport/test_algorithms.rb
=> Support new private key format for other than ed25519 keys

.rubocop.yml, CHANGES.txt, lib/net/ssh/authentication/ed25519.rb, lib/net/ssh/key_factory.rb, test/authentication/test_ed25519.rb
=> Encrypted openssh keys were not asked for passphrase

lib/net/ssh/known_hosts.rb
This makes two changes to known_hosts parsing:
* Only go through the work of building a regex for pattern matching if
the entry has pattern characters (* and ?). This was ~75% performance
improvement in the case where no patterns are being used.
* Use simple string splitting instead of a string scanner when parsing a
single line. This was ~20% performance improvement.
Together these changes entail ~80% reduction in parsing time with no
change in behavior. In a case with a large (20k entries) known_hosts
file, the time was reduced from 350ms to 65ms.
=> Improve performance of known_hosts parsing

README.md
=> Add Openssl requirement in Readme

lib/net/ssh/transport/constants.rb, lib/net/ssh/transport/kex/diffie_hellman_group14_sha1.rb, lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb, lib/net/ssh/transport/kex/diffie_hellman_group_exchange_sha1.rb, lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb, lib/net/ssh/transport/kex/ecdh_sha2_nistp384.rb, lib/net/ssh/transport/kex/ecdh_sha2_nistp521.rb
- Move some code in the good place (Constant)
- Remove already include modules
- Define properly the get_p and get_g method to handle inheritance.
=> Refactoring kex

lib/net/ssh/transport/cipher_factory.rb
=> Remove check because Openssl 1.0.1 introduice aes-ctr

lib/net/ssh/transport/hmac.rb
=> Modernize OpenSSL SHA2 implementation

CHANGES.txt
Noticed spelling of my namn was wrong in the CHANGES.txt-file, this fixes it.
Sorry for the brief commit description - did this on my phone.
=> Fix spelling

lib/net/ssh/transport/algorithms.rb, lib/net/ssh/transport/kex.rb, test/transport/test_algorithms.rb
=> Fix kex algorithm name

lib/net/ssh/transport/packet_stream.rb, test/integration/playbook.yml, test/integration/test_curve25519sha256.rb, test/integration/test_hmac_etm.rb
- Imrove error message with corrupted hmac
- Added basic hmac integration tests
=> Added new basic hmac integration test for etm

README.md
Minor readme improvements.
I also wanted to add a comment to clarify this, especially the passed block:
`ssh.loop { true }
`
...but I don't understand completely what it does.
=> Minor improvements to README.md.

CHANGES.txt, lib/net/ssh/transport/algorithms.rb, test/transport/test_algorithms.rb
=> Revert "Make hmac-sha2-{256,512}-etm opt-in"

lib/net/ssh/authentication/agent.rb, test/authentication/test_agent.rb
Provide methods to use agent locking and unlocking with a password.
I am not sure how to test this properly.
=> Add ssh agent lock and unlock

lib/net/ssh/transport/algorithms.rb, lib/net/ssh/transport/kex.rb, lib/net/ssh/transport/kex/diffie_hellman_group14_sha256.rb, test/transport/kex/test_diffie_hellman_group14_sha1.rb, test/transport/kex/test_diffie_hellman_group14_sha256.rb, test/transport/kex/test_diffie_hellman_group1_sha1.rb, test/transport/test_algorithms.rb
=> Add support for diffie-hellman-group14-sha256, fixes #794

.github/workflows/ci.yml, net-ssh.gemspec
=> Drop old ruby versions

.github/workflows/ci.yml
Update python version for integrations tests.
=> Update python test

.github/workflows/ci-with-docker.yml, Dockerfile.openssl3
Add unit test with docker and openssl 3.0
#857 #843
=> Add unit-test for openssl 3

CHANGES.txt
See https://github.com/net-ssh/net-ssh/issues/870#issuecomment-1306064905
Fixes #870
/cc @mfazekas
=> Add 7.0.0 + 7.0.1 to CHANGES.txt

.rubocop_todo.yml, lib/net/ssh/transport/aes128_gcm.rb, lib/net/ssh/transport/aes256_gcm.rb, lib/net/ssh/transport/algorithms.rb, lib/net/ssh/transport/cipher_factory.rb, lib/net/ssh/transport/gcm_cipher.rb, lib/net/ssh/transport/hmac/abstract.rb, lib/net/ssh/transport/packet_stream.rb, lib/net/ssh/transport/state.rb, test/integration/README.md, test/integration/playbook.yml, test/integration/test_gcm_cipher.rb, test/transport/test_algorithms.rb, test/transport/test_cipher_factory.rb, test/transport/test_packet_stream.rb
Close https://github.com/net-ssh/net-ssh/issues/834
=> feat: Add support for aes(128|256)gcm
